"""Health endpoint smoke test generated by Kodiak."""

import asyncio

from kodiak.api.routers.health import health


def test_health_endpoint_reports_healthy() -> None:
    assert asyncio.run(health()) == {"status": "healthy"}
